[project]
name = "apps"
version = "0.1.0"
description = "Apps"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "pymongo>=4.16.0",
    "python-dotenv>=1.2.1",
]
